version: '3'
services:
  micro:
    container_name: micro
    image: snowplow/snowplow-micro:1.0.0
    volumes:
      - ./micro:/config
    restart: always
    ports:
      - "9090:9090"
    command: "--collector-config /config/micro.conf --iglu /config/iglu.json"

  web:
    container_name: web
    build:
      context: .
      dockerfile: .docker/snowplow-rental/Dockerfile
    env_file:
      - .env
    volumes:
      - ./snowplow-rental:/snowplow-rental
    ports:
      - "3000:3000"